<% raise NotImplementedError, "Sorry, the 'default' theme is broken, please try using 'bridgepdx' and run 'rake bridgepdx:styles' to download the latest styles. See themes/README.txt for information on how to set the current theme." %>

# Organization running event:
organization: 'Ignite Anytown'

# Breadcrumbs that are always visible, each breadcrumb is a name and URI:
breadcrumbs:
  - ['Ignite Anytown', 'http://www.igniteanytown.com/']
  - ['Proposals', '/proposals/']

# Timezone for dates in this application:
timezone: 'Pacific Time (US & Canada)'
